/project-folder
    index.html
    style.css
    script.js
    /static
        /img
            bg_stars.png
            case1.png
            case2.png
            case3.png
            rocket.png
            star_icon.png
